### ISSUE TITLE
请问能否支持云台控制？

### ISSUE THREAD

**Issue by get2bad** [lkqm/hcnetsdk-java#1]
能否支持云台控制？
比如说预设点、上下左右移动等。
如果可以的话，能否添加基本的使用文档/以及支持的功能简介

**Comment by lkqm** [comment]
谢谢你的建议，我先看下海康文档，再决定是否有二次封装的必要，底层sdk功能太多了!

**Comment by lkqm** [comment]
`0.0.2-SNAPSHOT` 已经添加云台相关接口`HikDeviceTemplate.ptzXxx, HikDevice.ptzXxx`, 如果有不满足需求的地方可以直接调用原生sdk, 或 透传方法实现 关于相关概念的文档还是需要看官方文档，后续再考虑添加详细文档.
