### ISSUE TITLE
关于MacOS SDK的问题

### ISSUE THREAD

**Issue by cky-thinker** [lkqm/hcnetsdk-java#2]
我在海康威视的官方没有找到MacOS对应的SDK库，想问一下大佬项目里面的dylib是哪里下载的

**Comment by lkqm** [comment]
可以给官网提供的技术支持邮箱发送邮件，索取macos的sdk

**Comment by cky-thinker** [comment]
大佬，你还留有技术支持的邮箱吗？能不能把地址给我发一份，我在官网找半天没找到... 

本人邮箱： 759891347@qq.com

**Comment by lkqm** [comment]
邮箱清除过一次，找不到了

**Comment by lkqm** [comment]
直接使用项目里面提供的应该也可以
