### ISSUE TITLE
请问一下怎么初始化sdk路径

### ISSUE THREAD

**Issue by gabrielxvx** [lkqm/hcnetsdk-java#5]

**Comment by lkqm** [comment]
是指的本地依赖dll,so依赖库吗？JnaPathUtils这个工具约定了一个目录，只需要main方法内调用即可

**Comment by gabrielxvx** [comment]
感谢，在问一下 HikDevice device = new HikDevice(hcnetsdk, ip, port, user, password); 怎么判断是否登录成功

**Comment by lkqm** [comment]
result有对应方法，构造hcnetdevice不会登录，建议用template这个封装的不太好

**Comment by gabrielxvx** [comment]
hikDeviceTemplate.login()方法返回错误。

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.Error: Structure.getFieldOrder() on class com.github.lkqm.hcnet.HCNetSDK$NET_DVR_USER_LOGIN_INFO does not provide enough names [0] ([]) to match declared fields [8] ([bUseAsynLogin, byRes2, byUseTransport, cbLoginResult, sDeviceAddress, sPassword, sUserName, wPort])] with root cause

**Comment by lkqm** [comment]
跑下单元测试，也有可能是本地依赖库版本不兼容问题

**Comment by gabrielxvx** [comment]
有点头大😂，解决不了，感谢老哥的帮助，老哥有空能写个demo就完美了

**Comment by gabrielxvx** [comment]
😂😂我自己引入的jna版本过高，忘记移除了
