### ISSUE TITLE
请问一下如何获取NVR在线通道列表数量及通道名称？

### ISSUE THREAD

**Issue by gabrielxvx** [lkqm/hcnetsdk-java#6]

**Comment by lkqm** [comment]
HikResult<HCNetSDK.NET_DVR_IPPARACFG> channelResult = deviceTemplate.getDvrConfig(userId, HCNetSDK.NET_DVR_GET_IPPARACFG, 33, HCNetSDK.NET_DVR_IPPARACFG.class);

建议查哈官方的SDK的文档
